### ISSUE TITLE
Timeouts when calling `ensureToken` and no session exists

### ISSUE THREAD

**Issue by ramon-prieto** [Authress/authress-login.js#51]
Previously we had code checking the user session existence and then calling the ensure token.

This same code started to raise timeout issues when calling `ensureToken` if the `userSessionExists` is false.

Adding an if condition fixes the problem. Is this expected behavior?

```ts
const loggedIn = await client.userSessionExists()
        if (loggedIn) {
          const token = await client.ensureToken({})
          setSessionToken(token)
        }
```

**Comment by wparad** [comment]
Definitely. `ensureToken` attempts to wait for a token to be available. It attempts to block code execution until one is. The reason for this is that `useSessionExists` and `authenticate` might be called in a separate thread or a separate browser tab. When this happens multiple user actions or site code flows might result in many API requests to your backend all depending on `ensureToken`. Without the block, all these requests would be sent without a token (worst case) or throw an error everywhere in your code based (better case).

When a user session exists but the token is expired, instead we use the session to generate a new token. To prevent the race condition and causing the API requests that depend on a valid token from throwing error, `ensureToken` blocks (best case)

But what if there is no session, and the user must log in?

In the past `ensureToken` blocked forever, however this can create an unexpected situation in your site where the code "gets stuck", because methods that do that are often unexpected in libraries. So instead we enable a timeout for when you feel how long it is reasonable to wait for a token. The default timeout is set to be 5 seconds.

`ensureToken` seeks to never return `null`, as that can create a `pit of failure`, instead it throws.

The recommended flow for interacting with the login SDK could be instead something like this:
(Site Auth location)
```js
const loggedIn = await client.userSessionExists();
if (!loggedIn) {
  await client.authenticate();
  return;
}

// And then in some other code wherever you need to the token:
(site 1 code)
const token = await client.ensureToken();
```

A second thing I see looking at the library code, is that `ensureToken` actually already calls userSessionExists. So for the exact code you have, you can simplify it to be:

(site 1 code)
```js
try {
  const token = await client.ensureToken();
  setSessionToken(token);
} catch (error) {
  // Do something else
    setSessionToken(null);
}
```
However I will say I'm not totally user what `setSessionToken` is doing, that looks to be some sort of token state management. So I can imagine somewhere in your site you calling `getSessionToken` in a "site 2 code". I called these "site 1" and "site 2" to indicate that there are in different places in your code base.

Instead, I would delete all the "site 1" code and at "site 2" where you are presumably calling your own function `getSessionToken`, I would directly call into the library `const token = await client.ensureToken()`.

As this is expected I'm going to close this issue, but if there are additional questions about this, feel free to keep commenting.
